/** Core SEO keyword clusters for TeacherPoint (learning / tutoring marketplace). */
export const SEO_KEYWORDS = {
  core: [
    "teacher",
    "tutors",
    "online tutors",
    "online teachers",
    "students",
    "learning",
    "teaching",
    "tutoring",
    "coaching",
    "verified tutors",
    "qualified tutors",
    "highly qualified teachers",
    "find tutors",
    "search tutors",
    "local tutors",
    "home tutors",
    "tutors online",
    "tutors world",
    "teacher rankings",
    "ratings",
    "reviews",
    "feedback",
    "testimonials",
  ],
  trust: [
    "verified",
    "proof checked",
    "id proof",
    "address proof",
    "address proof checked",
    "certifications",
    "certificates checked",
    "trusted website",
    "stay safe",
    "safe learning",
  ],
  subjects: [
    "python",
    "java",
    "javascript",
    "jquery",
    "php",
    "html",
    "programming",
    "computer science",
    "data structures",
    "algorithm",
    "dbms",
    "computer networking",
    "digital electronics",
    "analog electronics",
    "basic electronics",
    "electrical engineering",
    "mechanical engineering",
    "civil engineering",
    "engineering mechanics",
    "fluid mechanics",
    "thermodynamics",
    "control systems",
    "physics",
    "chemistry",
    "biology",
    "maths",
    "statistics",
    "economics",
    "accountancy",
    "business management",
    "financial management",
    "company law",
    "income tax",
    "ielts",
    "english",
    "german",
    "french",
    "geography",
    "history",
    "psychology",
    "sociology",
    "political science",
    "environmental science",
    "microbiology",
    "biochemistry",
    "biotechnology",
    "zoology",
    "music",
    "communication skills",
    "academic writing",
    "selenium webdriver",
    "adobe photoshop",
    "autocad",
    "science",
    "subject",
    "skills",
    "top subjects",
  ],
  jobs: [
    "teaching jobs",
    "online teaching",
    "home teaching",
    "tutor jobs",
    "applying jobs",
    "apply application",
    "application process",
    "jobs",
    "earn",
    "refer earn",
  ],
  commerce: [
    "pricing",
    "premium membership",
    "paid",
    "pay teachers",
    "coins pricing",
    "free website",
    "buy sell",
    "lesson plans",
    "research papers",
    "assignments",
    "projects",
    "dissertations",
  ],
  legal: [
    "terms",
    "privacy policy",
    "refund policy",
    "contact",
    "faqs",
    "support",
  ],
  geo: [
    "local",
    "local area",
    "world",
    "countries",
    "time zones",
    "online teachers time zones",
  ],
} as const;

/** Flat deduplicated list for meta keywords tag (keep under ~20 for best practice). */
export function keywordsForPage(page: string): string[] {
  if (PAGE_KEYWORD_SETS[page]) return PAGE_KEYWORD_SETS[page];
  return [...SEO_KEYWORDS.core.slice(0, 12), "learning", "teaching", "students", "online"];
}

export const PAGE_KEYWORD_SETS: Record<string, string[]> = {
  "/": [
    ...SEO_KEYWORDS.core.slice(0, 8),
    "find local tutors",
    "online teaching",
    "learning resources",
    "free",
    "students teachers",
    "thousands students",
  ],
  "/tutors": [
    "find tutors",
    "search tutors",
    "qualified tutors",
    "verified tutors",
    "ratings reviews",
    "subject filter",
    "local tutors",
    "online tutors",
    "highly qualified",
  ],
  "/courses": [
    "online courses",
    "programming",
    "python",
    "java",
    "data structures",
    "certificates",
    "learning",
    "digital teaching",
  ],
  "/tutor-jobs": [
    "teaching jobs",
    "tutor jobs",
    "online teaching",
    "home tutors",
    "applying jobs",
    "apply application",
  ],
  "/pricing": [
    "pricing",
    "premium membership",
    "coins pricing",
    "pay teachers",
    "free",
    "paid",
  ],
  "/faq": ["faqs", "help", "learning", "tutors", "teachers", "support"],
  "/reviews": ["reviews", "testimonials", "ratings", "feedback", "teacher rankings"],
  "/privacy": ["privacy policy", "terms", "stay safe", "data protection"],
  "/terms": ["terms", "privacy policy", "refund policy", "legal"],
  "/refund": ["refund policy", "cancellation", "pricing", "payments"],
  "/contact": ["contact", "support", "help", "address"],
  "/marketplace": ["buy sell", "students", "lesson notes", "educational tools", "store"],
  "/post-requirement": ["post requirement", "find tutors", "coaching", "tutoring", "students"],
  "/workshops": ["workshops", "online teaching", "learning", "tutors", "students"],
  "/online-tutors": ["online tutors", "tutors online", "online teachers", "subjects"],
  "/home-tutors": ["home tutors", "local tutors", "find local", "teaching"],
  "/teaching-jobs": ["teaching jobs", "online teaching", "home teaching", "apply jobs"],
};

export const POPULAR_SUBJECT_LINKS: { label: string; subject: string }[] = [
  { label: "Python programming", subject: "python" },
  { label: "Java", subject: "java" },
  { label: "JavaScript & jQuery", subject: "javascript" },
  { label: "Data structures & algorithms", subject: "data structures" },
  { label: "Computer science", subject: "computer science" },
  { label: "Physics", subject: "physics" },
  { label: "Chemistry", subject: "chemistry" },
  { label: "Mathematics", subject: "maths" },
  { label: "Biology", subject: "biology" },
  { label: "English & IELTS", subject: "english" },
  { label: "Economics", subject: "economics" },
  { label: "Accountancy", subject: "accountancy" },
  { label: "Electrical engineering", subject: "electrical engineering" },
  { label: "Mechanical engineering", subject: "mechanical engineering" },
  { label: "Civil engineering", subject: "civil engineering" },
  { label: "Statistics", subject: "statistics" },
  { label: "Psychology", subject: "psychology" },
  { label: "Business management", subject: "business management" },
  { label: "Communication skills", subject: "communication skills" },
  { label: "Selenium WebDriver", subject: "selenium webdriver" },
  { label: "Adobe Photoshop", subject: "adobe photoshop" },
  { label: "AutoCAD", subject: "autocad" },
  { label: "Income tax", subject: "income tax" },
  { label: "Company law", subject: "company law" },
];
