/** Core SEO keyword clusters for TeacherPoint (learning / tutoring marketplace). */
export const SEO_KEYWORDS = {
  core: [
    "teacher",
    "tutors",
    "online tutors",
    "online teachers",
    "students",
    "learning",
    "teaching",
    "tutoring",
    "coaching",
    "verified tutors",
    "qualified tutors",
    "highly qualified teachers",
    "find tutors",
    "search tutors",
    "local tutors",
    "home tutors",
    "tutors online",
    "tutors world",
    "teacher rankings",
    "ratings",
    "reviews",
    "feedback",
    "testimonials",
  ],
  trust: [
    "verified",
    "proof checked",
    "id proof",
    "address proof",
    "address proof checked",
    "certifications",
    "certificates checked",
    "trusted website",
    "stay safe",
    "safe learning",
  ],
  subjects: [
    "python",
    "java",
    "javascript",
    "jquery",
    "php",
    "html",
    "css",
    "react",
    "programming",
    "computer science",
    "data structures",
    "algorithm",
    "machine learning",
    "artificial intelligence",
    "data science",
    "dbms",
    "computer networking",
    "digital electronics",
    "analog electronics",
    "basic electronics",
    "electrical engineering",
    "mechanical engineering",
    "civil engineering",
    "engineering mechanics",
    "fluid mechanics",
    "thermodynamics",
    "control systems",
    "physics",
    "chemistry",
    "biology",
    "maths",
    "mathematics",
    "statistics",
    "economics",
    "accountancy",
    "business management",
    "financial management",
    "company law",
    "income tax",
    "marketing",
    "digital marketing",
    "ielts",
    "toefl",
    "english",
    "spoken english",
    "german",
    "french",
    "spanish",
    "arabic",
    "hindi",
    "geography",
    "history",
    "psychology",
    "sociology",
    "political science",
    "environmental science",
    "microbiology",
    "biochemistry",
    "biotechnology",
    "zoology",
    "music",
    "communication skills",
    "academic writing",
    "selenium webdriver",
    "adobe photoshop",
    "autocad",
    "neet",
    "jee",
    "gate",
    "upsc",
    "sat",
    "gre",
    "gmat",
    "science",
    "subject",
    "skills",
    "top subjects",
  ],
  jobs: [
    "teaching jobs",
    "online teaching",
    "home teaching",
    "tutor jobs",
    "applying jobs",
    "apply application",
    "application process",
    "jobs",
    "earn",
    "refer earn",
  ],
  commerce: [
    "pricing",
    "premium membership",
    "paid",
    "pay teachers",
    "coins pricing",
    "free website",
    "buy sell",
    "lesson plans",
    "research papers",
    "assignments",
    "projects",
    "dissertations",
  ],
  legal: [
    "terms",
    "privacy policy",
    "refund policy",
    "contact",
    "faqs",
    "support",
  ],
  geo: [
    "local",
    "local area",
    "world",
    "countries",
    "time zones",
    "online teachers time zones",
  ],
} as const;

/** Flat deduplicated list for meta keywords tag (keep under ~20 for best practice). */
export function keywordsForPage(page: string): string[] {
  if (PAGE_KEYWORD_SETS[page]) return PAGE_KEYWORD_SETS[page];
  return [...SEO_KEYWORDS.core.slice(0, 12), "learning", "teaching", "students", "online"];
}

export const PAGE_KEYWORD_SETS: Record<string, string[]> = {
  "/": [
    ...SEO_KEYWORDS.core.slice(0, 8),
    "find local tutors",
    "online teaching",
    "learning resources",
    "free",
    "students teachers",
    "thousands students",
  ],
  "/tutors": [
    "find tutors",
    "search tutors",
    "qualified tutors",
    "verified tutors",
    "ratings reviews",
    "subject filter",
    "local tutors",
    "online tutors",
    "highly qualified",
  ],
  "/courses": [
    "online courses",
    "programming",
    "python",
    "java",
    "data structures",
    "certificates",
    "learning",
    "digital teaching",
  ],
  "/tutor-jobs": [
    "teaching jobs",
    "tutor jobs",
    "online teaching",
    "home tutors",
    "applying jobs",
    "apply application",
  ],
  "/pricing": [
    "pricing",
    "premium membership",
    "coins pricing",
    "pay teachers",
    "free",
    "paid",
  ],
  "/faq": ["faqs", "help", "learning", "tutors", "teachers", "support"],
  "/reviews": ["reviews", "testimonials", "ratings", "feedback", "teacher rankings"],
  "/privacy": ["privacy policy", "terms", "stay safe", "data protection"],
  "/terms": ["terms", "privacy policy", "refund policy", "legal"],
  "/refund": ["refund policy", "cancellation", "pricing", "payments"],
  "/contact": ["contact", "support", "help", "address"],
  "/marketplace": ["buy sell", "students", "lesson notes", "educational tools", "store"],
  "/post-requirement": ["post requirement", "find tutors", "coaching", "tutoring", "students"],
  "/workshops": ["workshops", "online teaching", "learning", "tutors", "students"],
  "/online-tutors": ["online tutors", "tutors online", "online teachers", "subjects"],
  "/home-tutors": ["home tutors", "local tutors", "find local", "teaching"],
  "/teaching-jobs": ["teaching jobs", "online teaching", "home teaching", "apply jobs"],
};

/** Slug used in /tutors?subject=… search params (mirrors backend slugify). */
function subjectSlug(name: string): string {
  let s = name.toLowerCase().trim();
  if (s.startsWith(".")) s = `dot-${s.replace(/^\.+/, "")}`;
  return s
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Homepage “Top subjects & skills” — keep in sync with
 * backend/src/data/subjects.catalog-top.js (TOP_SUBJECTS_AND_SKILLS).
 */
export const TOP_SUBJECT_NAMES: string[] = [
  "Academic Writing",
  "Analog Electronics",
  "BioChemistry",
  "C/C++",
  "Commerce",
  "Computer Science",
  ".net",
  "English",
  "French",
  "HTML",
  "Jquery and JavaScript",
  "Microbiology",
  "Political Science",
  "R",
  "Statistics",
  "Accountancy",
  "Art and Craft",
  "Biology",
  "C#",
  "Communication Skills",
  "Control Systems",
  "Economics",
  "Environmental Science",
  "Geography",
  "IELTS",
  "Law",
  "Music",
  "Programming",
  "Science",
  "Strength of Materials",
  "Adobe Photoshop",
  "AutoCAD",
  "Biotechnology",
  "Chemistry",
  "Company Law",
  "DBMS",
  "Electrical Engineering",
  "Financial Management",
  "German",
  "Income Tax",
  "Maths",
  "PHP",
  "Psychology",
  "Selenium Webdriver",
  "Thermodynamics",
  "Algorithm & Data Structures",
  "Basic Electronics",
  "Business Management",
  "Civil Engineering",
  "Computer networking",
  "Digital Electronics",
  "Engineering Mechanics",
  "Fluid Mechanics",
  "History",
  "JAVA",
  "Mechanical",
  "Physics",
  "Python",
  "Sociology",
  "Zoology",
  "Mathematics",
  "Algebra",
  "Geometry",
  "Trigonometry",
  "Calculus",
  "Linear Algebra",
  "Differential Equations",
  "Probability",
  "Organic Chemistry",
  "Inorganic Chemistry",
  "Physical Chemistry",
  "Botany",
  "Genetics",
  "Anatomy",
  "Physiology",
  "Astronomy",
  "Earth Science",
  "Geology",
  "NEET",
  "JEE Main",
  "JEE Advanced",
  "CUET",
  "UPSC",
  "SSC",
  "Banking Exams",
  "CAT",
  "GATE",
  "SAT",
  "ACT",
  "GRE",
  "GMAT",
  "LSAT",
  "MCAT",
  "TOEFL",
  "PTE",
  "Duolingo English Test",
  "IB Mathematics",
  "IB Physics",
  "IB Chemistry",
  "IB Biology",
  "A-Level Maths",
  "A-Level Physics",
  "A-Level Chemistry",
  "GCSE Maths",
  "GCSE Science",
  "JavaScript",
  "TypeScript",
  "SQL",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Django",
  "Flask",
  "Spring Boot",
  "ASP.NET",
  "Kotlin",
  "Swift",
  "Go",
  "Rust",
  "Ruby",
  "MATLAB",
  "Machine Learning",
  "Artificial Intelligence",
  "Deep Learning",
  "Data Science",
  "Big Data",
  "Cloud Computing",
  "AWS",
  "Azure",
  "Google Cloud",
  "DevOps",
  "Docker",
  "Kubernetes",
  "Cybersecurity",
  "Ethical Hacking",
  "Blockchain",
  "Web Development",
  "Full Stack Development",
  "Mobile App Development",
  "Android Development",
  "iOS Development",
  "Flutter",
  "React Native",
  "Software Engineering",
  "Software Testing",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Linux",
  "Operating Systems",
  "Computer Architecture",
  "Game Development",
  "Unity",
  "Excel",
  "Power BI",
  "Tableau",
  "Salesforce",
  "Mechanical Engineering",
  "Electronics & Communication",
  "Electronics Engineering",
  "Computer Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Industrial Engineering",
  "Automobile Engineering",
  "Petroleum Engineering",
  "Structural Engineering",
  "Power Systems",
  "VLSI",
  "Embedded Systems",
  "Mechatronics",
  "Robotics",
  "Signal Processing",
  "Heat Transfer",
  "Machine Design",
  "Manufacturing Technology",
  "Surveying",
  "Building Materials",
  "Transportation Engineering",
  "Hydraulics",
  "Solid Mechanics",
  "Finite Element Analysis",
  "SolidWorks",
  "CATIA",
  "ANSYS",
  "MATLAB Simulink",
  "PLC Programming",
  "SCADA",
  "Medicine",
  "Nursing",
  "Pharmacy",
  "Dentistry",
  "Physiotherapy",
  "Pathology",
  "Pharmacology",
  "Public Health",
  "Nutrition & Dietetics",
  "First Aid",
  "Yoga",
  "Accounting",
  "Business Studies",
  "Marketing",
  "Digital Marketing",
  "SEO",
  "Content Marketing",
  "Human Resource Management",
  "Operations Management",
  "Project Management",
  "Supply Chain Management",
  "Entrepreneurship",
  "Finance",
  "Corporate Finance",
  "Investment Banking",
  "Stock Market",
  "Cost Accounting",
  "Auditing",
  "Taxation",
  "GST",
  "CA Foundation",
  "CA Intermediate",
  "CS Executive",
  "CFA",
  "CPA",
  "PMP",
  "Six Sigma",
  "Business Analytics",
  "E-commerce",
  "Corporate Law",
  "Criminal Law",
  "Constitutional Law",
  "Civil Law",
  "Contract Law",
  "Intellectual Property Law",
  "Labour Law",
  "Family Law",
  "International Law",
  "Legal Studies",
  "CLAT",
  "Spoken English",
  "English Grammar",
  "English Literature",
  "Creative Writing",
  "Public Speaking",
  "Hindi",
  "Sanskrit",
  "Urdu",
  "Bengali",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Kannada",
  "Malayalam",
  "Spanish",
  "Italian",
  "Portuguese",
  "Russian",
  "Japanese",
  "Korean",
  "Mandarin",
  "Chinese",
  "Arabic",
  "Dutch",
  "Turkish",
  "Latin",
  "Sign Language",
  "Philosophy",
  "Anthropology",
  "Archaeology",
  "Civics",
  "Social Studies",
  "International Relations",
  "Mass Communication",
  "Journalism",
  "Media Studies",
  "Gender Studies",
  "Religious Studies",
  "General Knowledge",
  "Current Affairs",
  "Logical Reasoning",
  "Quantitative Aptitude",
  "Verbal Ability",
  "Drawing",
  "Painting",
  "Sketching",
  "Fine Arts",
  "Graphic Design",
  "UI/UX Design",
  "Figma",
  "Illustrator",
  "InDesign",
  "After Effects",
  "Premiere Pro",
  "Video Editing",
  "Photography",
  "Fashion Design",
  "Interior Design",
  "Architecture",
  "Animation",
  "3D Modelling",
  "Blender",
  "Dance",
  "Vocal Music",
  "Guitar",
  "Piano",
  "Violin",
  "Drum",
  "Theatre",
  "Acting",
  "Personality Development",
  "Interview Preparation",
  "Resume Writing",
  "Soft Skills",
  "Leadership",
  "Time Management",
  "Critical Thinking",
  "Emotional Intelligence",
  "Career Counseling",
  "Study Skills",
  "Cooking",
  "Baking",
  "Baking & Pastry",
  "Tailoring",
  "Beauty & Makeup",
  "Fitness Training",
  "Personal Training",
  "Swimming",
  "Chess",
  "Astrology",
  "Vedic Maths",
  "Abacus",
  "Handwriting",
  "Calligraphy",
];

/** Crawlable subject links for homepage SEO + footer chips. */
export const POPULAR_SUBJECT_LINKS: { label: string; subject: string }[] = TOP_SUBJECT_NAMES.map(
  (label) => ({ label, subject: subjectSlug(label) }),
);
